//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exyte.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationAudit
    {
        public long Sno { get; set; }
        public long AuditId { get; set; }
        public string Opertaion { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual UserAudit UserAudit { get; set; }
    }
}
