//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exyte.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ToolCostingEntities : DbContext
    {
        public ToolCostingEntities()
            : base("name=ToolCostingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuList> MenuLists { get; set; }
        public virtual DbSet<MenuRole> MenuRoles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserAudit> UserAudits { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<OperationAudit> OperationAudits { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
    
        public virtual int GET_PIPE_ENGINEERITEMS_DETAILS(string dBName)
        {
            var dBNameParameter = dBName != null ?
                new ObjectParameter("DBName", dBName) :
                new ObjectParameter("DBName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PIPE_ENGINEERITEMS_DETAILS", dBNameParameter);
        }
    }
}
