//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exyte.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToolCostingEntities : DbContext
    {
        public ToolCostingEntities()
            : base("name=ToolCostingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MenuList> MenuLists { get; set; }
        public virtual DbSet<MenuRole> MenuRoles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserAudit> UserAudits { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<OperationAudit> OperationAudits { get; set; }
    }
}
