//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exyte.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAudit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserAudit()
        {
            this.OperationAudits = new HashSet<OperationAudit>();
        }
    
        public long Sno { get; set; }
        public long UserID { get; set; }
        public bool IsLogin { get; set; }
        public Nullable<System.DateTime> LoginOn { get; set; }
        public Nullable<System.DateTime> LogoutOn { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationAudit> OperationAudits { get; set; }
    }
}
